# Uncomment the next line to define a global platform for your project
platform :ios, 9.0

target 'UnsplashApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  pod 'RxSwift'
  pod 'RxSwiftExt'
  pod 'RxDataSources'
  pod 'R.swift'

  target 'UnsplashAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
